LUAC = luac

all: .tmp/main.lua.bin .tmp/i18n.lua.bin .tmp/social.lua.bin .tmp/dot.lua.bin .tmp/submit.lua.bin .tmp/parse.lua.bin .tmp/gamestate.lua.bin .tmp/pause.lua.bin .tmp/sounds.lua.bin .tmp/hud.lua.bin .tmp/game.lua.bin .tmp/menu.lua.bin .tmp/shop.lua.bin .tmp/score.lua.bin .tmp/powerup.lua.bin .tmp/modes.lua.bin .tmp/leaderboard.lua.bin .tmp/easing.lua.bin .tmp/gtween.lua.bin .tmp/scenemanager.lua.bin .tmp/GiderosCodingEasy.lua.bin .tmp/button.lua.bin .tmp/dataSaver.lua.bin .tmp/billing.lua.bin .tmp/ads.lua.bin

.tmp/main.lua.bin: main.lua
	$(LUAC) -o ".tmp/main.lua.bin" "main.lua"

.tmp/i18n.lua.bin: i18n.lua
	$(LUAC) -o ".tmp/i18n.lua.bin" "i18n.lua"

.tmp/social.lua.bin: social.lua
	$(LUAC) -o ".tmp/social.lua.bin" "social.lua"

.tmp/dot.lua.bin: dot.lua
	$(LUAC) -o ".tmp/dot.lua.bin" "dot.lua"

.tmp/submit.lua.bin: submit.lua
	$(LUAC) -o ".tmp/submit.lua.bin" "submit.lua"

.tmp/parse.lua.bin: parse.lua
	$(LUAC) -o ".tmp/parse.lua.bin" "parse.lua"

.tmp/gamestate.lua.bin: gamestate.lua
	$(LUAC) -o ".tmp/gamestate.lua.bin" "gamestate.lua"

.tmp/pause.lua.bin: pause.lua
	$(LUAC) -o ".tmp/pause.lua.bin" "pause.lua"

.tmp/sounds.lua.bin: sounds.lua
	$(LUAC) -o ".tmp/sounds.lua.bin" "sounds.lua"

.tmp/hud.lua.bin: hud.lua
	$(LUAC) -o ".tmp/hud.lua.bin" "hud.lua"

.tmp/game.lua.bin: game.lua
	$(LUAC) -o ".tmp/game.lua.bin" "game.lua"

.tmp/menu.lua.bin: menu.lua
	$(LUAC) -o ".tmp/menu.lua.bin" "menu.lua"

.tmp/shop.lua.bin: shop.lua
	$(LUAC) -o ".tmp/shop.lua.bin" "shop.lua"

.tmp/score.lua.bin: score.lua
	$(LUAC) -o ".tmp/score.lua.bin" "score.lua"

.tmp/powerup.lua.bin: powerup.lua
	$(LUAC) -o ".tmp/powerup.lua.bin" "powerup.lua"

.tmp/modes.lua.bin: modes.lua
	$(LUAC) -o ".tmp/modes.lua.bin" "modes.lua"

.tmp/leaderboard.lua.bin: leaderboard.lua
	$(LUAC) -o ".tmp/leaderboard.lua.bin" "leaderboard.lua"

.tmp/easing.lua.bin: classes/easing.lua
	$(LUAC) -o ".tmp/easing.lua.bin" "classes/easing.lua"

.tmp/gtween.lua.bin: classes/gtween.lua
	$(LUAC) -o ".tmp/gtween.lua.bin" "classes/gtween.lua"

.tmp/scenemanager.lua.bin: classes/scenemanager.lua
	$(LUAC) -o ".tmp/scenemanager.lua.bin" "classes/scenemanager.lua"

.tmp/GiderosCodingEasy.lua.bin: classes/GiderosCodingEasy.lua
	$(LUAC) -o ".tmp/GiderosCodingEasy.lua.bin" "classes/GiderosCodingEasy.lua"

.tmp/button.lua.bin: classes/button.lua
	$(LUAC) -o ".tmp/button.lua.bin" "classes/button.lua"

.tmp/dataSaver.lua.bin: classes/dataSaver.lua
	$(LUAC) -o ".tmp/dataSaver.lua.bin" "classes/dataSaver.lua"

.tmp/billing.lua.bin: classes/billing.lua
	$(LUAC) -o ".tmp/billing.lua.bin" "classes/billing.lua"

.tmp/ads.lua.bin: classes/ads.lua
	$(LUAC) -o ".tmp/ads.lua.bin" "classes/ads.lua"

